language: cpp

sudo: enabled
dist: trusty

compiler:
  - gcc

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libvulkan-dev

script:
  - ./build.sh

after_failure:
  - cat test/test-suite.log

after_success:
  - coveralls --exclude test --gcov-options '\-lp'

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

before_install:
    - eval "${MATRIX_EVAL}"
    - pip install --user cpp-coveralls
